"""Generate PortMapCoords.cs from MoffKalast/Sailwind-Map city polygons.

Source data is MIT licensed; see THIRD_PARTY_NOTICES.md.
"""
import json
import math
import urllib.request
from pathlib import Path

BASE = "https://raw.githubusercontent.com/MoffKalast/Sailwind-Map/main/assets/islands"

# Game port_name -> map city JSON path (under assets/islands/)
PORT_FILES = {
    "Gold Rock City": "alankh/cities/gold_rock_city_city.json",
    "Al'Nilem": "alankh/cities/alnilem_city.json",
    "Neverdin": "alankh/cities/neverdin_city.json",
    "Albacore Town": "alankh/cities/albacore_town_city.json",
    "Alchemist's Island": "alankh/cities/alchemists_island_city.json",
    "Al'Ankh Academy": "alankh/cities/alankh_academy_city.json",
    "Oasis": "alankh/cities/oasis_city_0.json",
    "Dragon Cliffs": "emerald/cities/dragon_cliffs_city.json",
    "Sanctuary": "emerald/cities/sanctuary_city.json",
    "Crab Beach": "emerald/cities/crab_beach_city.json",
    "New Port": "emerald/cities/new_port_city.json",
    "Sage Hills": "emerald/cities/sage_hills_city.json",
    "Serpent Isle": "emerald/cities/serpent_isle_city.json",
    "Fort Aestrin": "aestrin/cities/fort_aestrin_city_0.json",
    "Sunspire": "aestrin/cities/sunspire_city.json",
    "Mount Malefic": "aestrin/cities/mount_malefic_city.json",
    "Siren Song": "aestrin/cities/siren_song_city.json",
    "Eastwind": "aestrin/cities/eastwind_city.json",
    "Happy Bay": "bay/happy_bay_city.json",
    "Chronos": "chronos/chronos_city.json",
    "Kicia Bay": "firefish/cities/kicia_fire_fish_town_city.json",
    "Fire Fish Town": "firefish/cities/kicia_fire_fish_town_city.json",
    "On'na": "firefish/cities/senna_onna_city.json",
    "Sen'na": "firefish/cities/senna_onna_city.json",
    "Aestra Abbey": "aestrin/cities/aestra_abbey_city.json",
    "Fey Valley": "aestrin/cities/fey_valley_city.json",
    "Firefly Grotto": "aestrin/cities/firefly_grotto_city.json",
    "Turtle Island": "emerald/cities/turtle_island_city.json",
    "Dead Cove": "emerald/cities/dead_cove_city.json",
    "Old Ankh Town": "alankh/cities/old_ankh_town_city.json",
    "Mirage Mountain": "alankh/cities/mirage_mountain_city.json",
    "Saffron Island": "alankh/cities/saffron_city.json",
}


def centroid(coords):
    if isinstance(coords[0][0][0], (int, float)):
        ring = coords[0]
    else:
        ring = coords[0][0]
    lon = sum(p[0] for p in ring) / len(ring)
    lat = sum(p[1] for p in ring) / len(ring)
    return lon, lat


def fetch_json(path):
    url = f"{BASE}/{path}"
    with urllib.request.urlopen(url, timeout=30) as resp:
        return json.load(resp)


def main():
    entries = []
    for name, rel in sorted(PORT_FILES.items()):
        data = fetch_json(rel)
        lon, lat = centroid(data["coordinates"])
        entries.append((name, lon, lat))

    out = Path(__file__).resolve().parents[1] / "src" / "Routes" / "PortMapCoords.cs"
    lines = [
        "// Auto-generated by test/generate_port_map_coords.py — do not edit.",
        "// Source: MoffKalast/Sailwind-Map (MIT); see THIRD_PARTY_NOTICES.md.",
        "using System.Collections.Generic;",
        "",
        "namespace Routier",
        "{",
        "  internal static class PortMapCoords",
        "  {",
        "    private static readonly Dictionary<string, (float Lon, float Lat)> ByName =",
        "      new Dictionary<string, (float Lon, float Lat)>",
        "    {",
    ]
    for name, lon, lat in entries:
        esc = name.replace("\\", "\\\\").replace("\"", "\\\"")
        lines.append(f"      {{ \"{esc}\", ({lon:.6f}f, {lat:.6f}f) }},")
    lines += [
        "    };",
        "",
        "    internal static bool TryGet(string portName, out float lon, out float lat)",
        "    {",
        "      lon = lat = 0f;",
        "      if (string.IsNullOrEmpty(portName) || !ByName.TryGetValue(portName, out var pt))",
        "        return false;",
        "      lon = pt.Lon;",
        "      lat = pt.Lat;",
        "      return true;",
        "    }",
        "  }",
        "}",
        "",
    ]
    out.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {len(entries)} ports to {out}")


if __name__ == "__main__":
    main()
