// Auto-generated by test/generate_port_map_coords.py — do not edit.
// Source: MoffKalast/Sailwind-Map (MIT); see THIRD_PARTY_NOTICES.md.
using System.Collections.Generic;

namespace Routier
{
  internal static class PortMapCoords
  {
    private static readonly Dictionary<string, (float Lon, float Lat)> ByName =
      new Dictionary<string, (float Lon, float Lat)>
    {
      { "Aestra Abbey", (0.347491f, 40.357299f) },
      { "Al'Ankh Academy", (-5.367804f, 31.522603f) },
      { "Al'Nilem", (-5.446162f, 31.235325f) },
      { "Albacore Town", (-4.493054f, 30.817442f) },
      { "Alchemist's Island", (-4.867672f, 30.670925f) },
      { "Chronos", (22.421255f, 38.402008f) },
      { "Crab Beach", (4.889044f, 31.690624f) },
      { "Dead Cove", (4.285139f, 31.537603f) },
      { "Dragon Cliffs", (4.768415f, 31.341505f) },
      { "Eastwind", (0.216491f, 40.908829f) },
      { "Fey Valley", (0.742592f, 40.722077f) },
      { "Fire Fish Town", (2.890954f, 28.106332f) },
      { "Firefly Grotto", (0.798417f, 40.534040f) },
      { "Fort Aestrin", (0.629785f, 40.332422f) },
      { "Gold Rock City", (-4.850377f, 31.109307f) },
      { "Happy Bay", (3.580522f, 35.362622f) },
      { "Kicia Bay", (2.890954f, 28.106332f) },
      { "Mirage Mountain", (-4.501030f, 33.064955f) },
      { "Mount Malefic", (1.155128f, 39.929231f) },
      { "Neverdin", (-5.436069f, 30.886684f) },
      { "New Port", (4.743082f, 32.107471f) },
      { "Oasis", (-5.080308f, 32.744091f) },
      { "Old Ankh Town", (-5.018525f, 30.743394f) },
      { "On'na", (2.829839f, 28.286429f) },
      { "Saffron Island", (-4.193742f, 34.088261f) },
      { "Sage Hills", (4.509599f, 30.893504f) },
      { "Sanctuary", (5.133147f, 31.879633f) },
      { "Sen'na", (2.829839f, 28.286429f) },
      { "Serpent Isle", (4.398785f, 31.788089f) },
      { "Siren Song", (0.575433f, 40.753706f) },
      { "Sunspire", (0.929812f, 40.211581f) },
      { "Turtle Island", (5.256291f, 31.436583f) },
    };

    internal static bool TryGet(string portName, out float lon, out float lat)
    {
      lon = lat = 0f;
      if (string.IsNullOrEmpty(portName) || !ByName.TryGetValue(portName, out var pt))
        return false;
      lon = pt.Lon;
      lat = pt.Lat;
      return true;
    }
  }
}
